KEYCLOAK-15617
andymunro/keycloak-documentation pull request #24
Opened 2020-10-09 10:29 UTC by briandooley

Not sure if this should be a procedure, as the original module did not contain much material steps to make a procedure out of. Maybe a concept module instead?

2020-10-09 20:52 UTC, andymunro commented on server_admin/topics/clients/oidc/proc-using-a-service-account.adoc
> +In the `Service Account Roles` tab, you can configure the roles available to the service account for your client. These roles must be available in Role Scope Mappings (under the `Scope` tab) of your
I would convert this into two steps

. On the Scope tab, verify that you have roles or set `Full Scope Allowed` to ON.
. On the `Service Account Roles` tab, configure the roles available to this service account for your client.

2020-10-09 20:52 UTC, andymunro commented on server_admin/topics/clients/oidc/proc-using-a-service-account.adoc
> +. Click *Save*
Add a period.

2020-10-09 20:57 UTC, andymunro commented on server_admin/topics/clients/oidc/proc-using-a-service-account.adoc
> +.Prerequisites
We need a comma after _service account_ because it is followed by "which" not "that."

2020-10-09 20:58 UTC, andymunro commented on server_admin/topics/clients/oidc/proc-using-a-service-account.adoc
> +* You have selected your client in {project_name}.
You could think about making these steps 1 and 2 of the procedure.  I generally use prerequisites to help break up the procedure.  The three of us should probably talk about this.

2020-10-09 21:01 UTC, andymunro requested changes
I think the steps help, because there is a sequence.  The conceptual content may need to remain following the steps, because it may be too much to rework it.

2020-10-12 09:39 UTC, briandooley commented
Changes applied.

2020-10-12 20:39 UTC, andymunro approved these changes

2020-10-12 20:42 UTC, andymunro commented
@briandooley  Looks like there is a conflict in the topics.adoc file

<<<<<<< KEYCLOAK-15617
include::topics/clients/oidc/confidential.adoc[]
include::topics/clients/oidc/proc-using-a-service-account.adoc[]
=======
include::topics/clients/oidc/con-confidential-client-credentials.adoc[]
include::topics/clients/oidc/service-accounts.adoc[]
>>>>>>> admin-reuse

2020-10-14 11:16 UTC, briandooley commented
@andymunro I've resolved the conflict. I will let you have a look and make the final merge.

2020-10-15 15:55 UTC, merged

2020-10-15 15:55 UTC, andymunro commented
Thanks, merged.