KEYCLOAK-16234 initial commit
andymunro/keycloak-documentation pull request #41
Opened 2020-11-18 11:24 UTC by briandooley

2020-11-18 20:20 UTC, andymunro approved these changes
No changes. thanks for the rapid rework.  Once Joan provides her final user chapter, I will submit everything minus SSO protocols, then merge SSO protocols.

2020-11-24 16:39 UTC, andymunro commented on server_admin/topics.adoc
> -include::topics/sso-protocols/docker.adoc[]
Can you move these includes to the sso-protocols.adoc file?  That is the assembly where they go. 
Eventually I think that topics.adoc will only include the chapter head sections, like sso-protocols.adoc

2020-11-24 16:47 UTC, andymunro approved these changes
Excellent.  Looks like it follows all the rules.   I will merge once I have Joan's input on the Users chapter.

2020-11-30 16:24 UTC, andymunro commented
@briandooley There is still one conflict.  Otherwise, I am ready to merge it.

2020-12-07 19:06 UTC, andymunro commented on server_admin/topics.adoc
> +include::topics/clients/assembly-client-oidc.adoc[]
Looks like this include is in the wrong place.  It goes in the file:  clients/assembly-managing-clients.adoc.

2020-12-07 19:13 UTC, andymunro commented on server_admin/topics/sso-protocols/con-saml.adoc
> +[[_saml]]
I think there may be a problem with using two anchor ids.  Using CCutil on this caused an error, so best to remove it here.

2020-12-07 19:21 UTC, andymunro reviewed
@briandooley I suspect there are old versions of files that have the same anchors as the new ones.  The book built with MVN, but not with CCutil.  Somehow CCutil still finds the older files. For example, do you still have a file sso-protocols/saml.adoc?

We can review at tomorrow's synch up if that works.

2020-12-09 20:04 UTC, andymunro commented on server_admin/topics.adoc
> +<<<<<<< HEAD
Remove this line.

2020-12-09 20:05 UTC, andymunro commented on server_admin/topics.adoc
> +=======
Remove this line.

2020-12-09 20:30 UTC, andymunro commented on server_admin/topics/users/proc-enabling-terms-conditions.adoc
> += Terms and conditions
How about: "Enabling terms and conditions as a required action"

2020-12-09 20:30 UTC, andymunro requested changes
Just a couple of changes.

2020-12-16 09:29 UTC, briandooley commented
Have made the requested changes.

2020-12-16 17:20 UTC, andymunro approved these changes

2020-12-16 17:20 UTC, merged

2020-12-16 17:20 UTC, andymunro commented
Thanks, Brian. Merged.