Keycloak 15700
andymunro/keycloak-documentation pull request #43
Opened 2020-12-03 14:35 UTC by briandooley

2020-12-09 20:02 UTC, andymunro approved these changes

2020-12-09 20:03 UTC, andymunro commented
This one still has a few conflicting files.

2021-01-20 19:21 UTC, andymunro commented on server_admin/topics/admin-console-permissions/master-realm.adoc
> +It is possible to grant management privileges, for multiple realms in the system, to admin users within the `master` realm.
Change "It is possible to" to "You can"

2021-01-20 19:22 UTC, andymunro commented on server_admin/topics/admin-console-permissions/master-realm.adoc
> +Users with these roles can use that specific part of the administration console only.
Change "administration console" to "Admin Console"

2021-01-20 19:23 UTC, andymunro commented on server_admin/topics/admin-console-permissions/master-realm.adoc
> +Admins with the `manage-users` role can assign admin roles to users that only admins with the `manage-users` role have. For example, if an admin has the `manage-users` role but does not have the `man
Refer to a user with administrator rights as an “administrator,” not an admin.

2021-01-20 19:25 UTC, andymunro commented on server_admin/topics/clients/oidc/service-accounts.adoc
> +This is covered in the OAuth 2.0 specifiation under <<_client_credentials_grant,Client Credentials Grant>>.
This capability

2021-01-20 19:25 UTC, andymunro commented on server_admin/topics/clients/oidc/service-accounts.adoc
> +the `Service Accounts Enabled` switch is displayed.  You need to toggle this switch to ON.  Also make sure that you have
Remote "You need to"

2021-01-20 19:32 UTC, andymunro commented on server_admin/topics/realms/keys.adoc
> +{project_name}'s authentication protocols require cryptographic signatures and, in some cases, encryption.  {project_name} implements asymmetric key pairs (a private and public key) to do this.
change "to do this" to "address this situation."

2021-01-20 19:34 UTC, andymunro commented on server_admin/topics/realms/keys.adoc
Asterisks no backticks.

2021-01-20 19:35 UTC, andymunro commented on server_admin/topics/realms/keys.adoc
> +* Create new keys with the same priority and make the previous keys passive.
Make it "Creating"

2021-01-20 19:37 UTC, andymunro commented on server_admin/topics/realms/keys.adoc
> +. Click *Save*.
Asterisks

2021-01-20 19:37 UTC, andymunro commented on server_admin/topics/realms/keys.adoc
> +. Click *Save*.
Asterisks

2021-01-20 19:37 UTC, andymunro commented on server_admin/topics/realms/keys.adoc
> +. Click *Save*.
Asterisks

2021-01-20 19:38 UTC, andymunro commented on server_admin/topics/realms/keys.adoc
> +. Click the 'Active' tab.
Asterisks

2021-01-20 19:39 UTC, andymunro commented on server_admin/topics/realms/keys.adoc
> +. Click the 'Active' tab.
Asterisks

2021-01-20 19:39 UTC, andymunro commented on server_admin/topics/realms/keys.adoc
> +. Click the `Revocation` tab.
Asterisks

2021-01-20 19:41 UTC, andymunro requested changes
Thanks, Brian.  A few changes.

Also, I am not sure why the "service-accounts" file is in there, but I don't think it matter since we have a new file proc-using-a-service account.

2021-01-25 22:25 UTC, andymunro commented
Still a few changes requested above, but overall looks good.

2021-01-25 22:28 UTC, andymunro approved these changes

2021-01-26 08:49 UTC, briandooley commented
@andymunro Ok to merge this?

2021-01-26 15:58 UTC, andymunro commented
Will merge it today @briandooley

2021-01-26 22:46 UTC, merged

2021-01-26 22:46 UTC, andymunro commented
Merged. Thanks @briandooley