KEYCLOAK-15749 Rewords SSSD
andymunro/keycloak-documentation pull request #48
Opened 2021-01-22 12:47 UTC by briandooley

2021-02-23 21:44 UTC, andymunro commented on server_admin/topics/user-federation.adoc
> +Organizations can have databases containing information, passwords, and other credentials. Typically it is impossible to migrate existing data storage to a {project_name} deployment so {project_name}
Change "it is impossible" to "you cannot"

2021-02-23 21:44 UTC, andymunro commented on server_admin/topics/user-federation.adoc
> +When a user attempts to log in, {project_name} examines its user storage to find that user. If {project_name} does not find the user, {project_name} iterates over each User Storage provider for the r
change "its" to "that user's"

2021-02-23 21:46 UTC, andymunro commented on server_admin/topics/user-federation.adoc
> +. Click the *Add Provider* drop-down list.
drop "drop-down" per IBM standards

2021-02-23 21:48 UTC, andymunro commented on server_admin/topics/user-federation.adoc
> +. Click the provider type you want to add, and {project_name} brings you to that provider's configuration page.
Change " add, and {project_name}" to "add.  {project_name}"

2021-02-23 21:49 UTC, andymunro commented on server_admin/topics/user-federation.adoc
> +If a User Storage Provider fails, you may not be able to log in and view users in the admin console. {project_name} does not detect failures when using a Storage Provider to lookup a user, so it canc
Admin Console

2021-02-23 21:52 UTC, andymunro commented on server_admin/topics/user-federation.adoc
> +{project_name} searches the local {project_name} user database first to resolve users before any LDAP or custom User Storage Provider. Consider creating an admin account stored in the local {project_
From the Bible: Refer to a user with administrator rights as an “administrator,” not an admin.

2021-02-23 21:53 UTC, andymunro commented on server_admin/topics/user-federation.adoc
> +Each LDAP and custom User Storage Provider has an `enable` toggle on its admin console page. Disabling the User Storage Provider skips the provider when performing queries, so you can view and log in
Admin Console

2021-02-23 21:54 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +. Click the *Add Provider* drop-down list.
drop "drop-down" per IBM standards

2021-02-23 21:55 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +. Click _ldap_, and {project_name} brings you to the LDAP configuration page.
Select *ldap*
https://docs.engineering.redhat.com/display/CCSENABLE/GUI+elements

2021-02-23 22:00 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +{project_name} imports users from LDAP into the local {project_name} user database. This copy of the user database synchronizes on-demand or through a periodic background task. The exception to this
suggest "An exception exists for synchronizing passwords."

2021-02-24 09:48 UTC, briandooley commented
@andymunro Changes made.

2021-02-24 20:41 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +Users and admins can modify user metadata, users through the <<_account-service, User Account Service>>, and admins through the admin console. The `Edit Mode` configuration on the LDAP configuration
administrators

2021-02-24 20:43 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +It is impossible to change username, email, first name, last name, and other mapped attributes. {project_name} shows an error anytime a user attempts to update these fields. Password updates are not
You cannot change the username, ...

2021-02-24 20:44 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +It is possible to change username, email, first name, last name, and other mapped attributes and passwords and synchronize them automatically with the LDAP store.
You cannot change the username, ...

2021-02-24 20:44 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +{project_name} stores changes to username, email, first name, last name, and passwords in {project_name} local storage, so the admin must synchronize this data back to LDAP. In this mode, {project_na
"the" username
administrator

2021-02-24 20:47 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +When {project_name} creates the LDAP provider, {project_name} also creates a set of initial <<_ldap_mappers,LDAP mappers>>. {project_name} configures these mappers based on a combination of the `Vend
Change backticks to asterisks

2021-02-24 20:48 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +When you configure a secure connection URL to your LDAP store (for example,`ldaps://myhost.com:636'), {project_name} uses SSL to communicate with the LDAP server. You must configure a truststore on t
Drop the "You must"
Configure a truststore on the {project_name} server side so that {project_name} can  trust the SSL connection to LDAP.

2021-02-24 20:56 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +If you set the *Import Users* option, the LDAP Provider handles importing LDAP users into the {project_name} local database. The first time a user logs in, the LDAP provider imports the LDAP user int
Not certain what the original actually means, but I think we need to move "only" from the end of the sentence to the "you will only see.." or make it "you will see only..."
However, if you understand it better, leave it as is.

2021-02-24 20:56 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +If you want to sync all LDAP users into the {project_name} database, configure and enable the `Sync Settings` on the LDAP provider configuration page.
replace backticks with asterisks

2021-02-24 20:57 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +The best way to synchronize is to click the `Synchronize all users` button when you first create the LDAP provider, then set up periodic synchronization of changed users.
replace backticks with asterisks

2021-02-24 21:00 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +This mapper specifies which LDAP attribute maps to the attribute of the {project_name} user. For example, you can configure the `mail` LDAP attribute to the `email` attribute in the {project_name} da
a one-to-one mapping always exists.

2021-02-24 22:02 UTC, andymunro requested changes
Looks of great reworking.  A few suggestions.  I am trying to catch up with you.

2021-02-24 22:02 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +This mapper is specific to Microsoft Active Directory (MSAD). It can integrate the MSAD user account state into the {project_name} account state, such as enabled account or  expired password. This ma
Change" password, and there will be"
TO
"password. The result is"

2021-02-24 22:02 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +User Attribute mappers that map basic {project_name} user attributes, such as username, firstname, lastname, and email, to corresponding LDAP attributes. You can extend these and provide your own add
Admin Console

2021-02-24 22:02 UTC, andymunro commented on server_admin/topics/user-federation/ldap.adoc
> +By default, LDAP servers such as MSAD, RHDS, or FreeIPA hash and salt passwords. Other LDAP servers such as OpenLDAP or ApacheDS store the passwords in plain-text unless you use the _LDAPv3 Password
Drop "You must" -- no meaning lost.

2021-02-24 22:02 UTC, andymunro commented on server_admin/topics/user-federation/sssd.adoc
> +SSSD integrates with the FreeIPA identity management (IdM) server, providing authentication and access control. With this integration, {project_name} can  authenticate against privileged access manag
extra space after "can"

2021-02-24 22:02 UTC, andymunro commented on server_admin/topics/user-federation/sssd.adoc
> ++
Generally we use this format as in the bible
[source,bash,subs=+attributes]
However, I am not sure what's needed.

2021-02-24 22:02 UTC, andymunro commented on server_admin/topics/user-federation/sssd.adoc
> +[source]
[source,bash,subs=+attributes]

We should probably use sync up to discuss this.

2021-02-24 22:02 UTC, andymunro commented on server_admin/topics/user-federation/sssd.adoc
> +After the installation, you must configure a federated SSSD store.
drop "you must"

2021-02-24 22:02 UTC, andymunro commented on server_admin/topics/user-federation/sssd.adoc
> +. From the left menu, click *User Federation*.
Click *User Federation* in the menu.

2021-02-24 22:02 UTC, andymunro commented on server_admin/topics/user-federation/sssd.adoc
> +. Click the *Add Provider* drop-down list.
drop "drop-down*.
. From the  *Add Provider* list, select *sssd*.   (see https://docs.engineering.redhat.com/display/CCSENABLE/GUI+elements)  The *sssd* configuration page displays.  (see the bible)

2021-02-25 10:50 UTC, briandooley commented
@andymunro Changes made.

2021-02-25 20:16 UTC, andymunro approved these changes
Okay, to set to Resolved

2021-02-25 20:16 UTC, merged